name: Metrics
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.13
        with:
          token: ${{ secrets.METRICS_TOKEN }}
